library(plotly)
shinyUI(fluidPage(
                titlePanel("Developing Data Products Course Project"),
                sidebarLayout(
                        sidebarPanel(
                                h5("Side Panel"),
                                sliderInput("CPIslider","What is the Corruption Index of the Country?",1,10,0,step=0.1),
                                checkboxInput("showModel1", "Show/Hide Model 1", value = TRUE),
                                checkboxInput("showModel2", "Show/Hide Model 2", value=TRUE),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                selectInput("DataInput", 
                                            label = "Choose a data time series",
                                            choices = c("Home Value"="Home.Value","Structure Cost"="Structure.Cost","Land Value"="Land.Value","Home Price Index"="Home.Price.Index","Land Price Index"="Land.Price.Index"),                                          
                                            selected = "Home.Value"),
                                selectInput("StateInput", 
                                            label = "Choose a state",
                                            choices = c("AK","AL","AR","AZ","CA","CO","CT","DE","FL","GA","HI","IA","ID","IL","IN","KS","KY","LA","MA","MD","ME","MI","MN","MO","MS","MT","NC","ND","NE","NH","NJ","NM","NV","NY","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VA","WA","WV","WY","DC"),                                          
                                selected = "AK"),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br(),
                                br()
                        ),
                        mainPanel(
                                plotlyOutput("plot1"),
                                strong("Predicted HDI from linear regression model"),
                                textOutput("pred1"),
                                strong("Predicted HDI from quadratic regression model"),
                                textOutput("pred2"),
                                br(),
                                strong("Corruption Perception Index"),"- Published by Transparency International since 1995 annually, ranking countries by their perceived levels of corruption, as determined by expert assessments and opinion surveys",
                                br(),
                                strong("Human Development Index"),"- A composite statistic of life expectancy, education, and per capita income indicators, which are used to rank countries",
                                br(),
                                br(),
                                br(),
                                br(),
                                h4(textOutput("text")),
                                plotlyOutput("plot2",width="800px",height="400px"),
                                
                                strong("Home Value"), "- The average value of owner-occupied houses",
                                br(),
                                strong("Structure Cost"), "- The replacement cost, after accounting for depreciation, of a typical owner-occupied housing structure for each state.",
                                br(),
                                strong("Land Value"),"- The Home Value less the replacement Structure Cost",
                                br(),
                                strong("Home Price Index"), "- Based on the adjusted FHFA indexes used to compute the Home Value series",
                                br(),
                                strong("Land Price Index"), "- The Land Price Index is calculated with the method of Davis and Heathcote (2007) using estimates of the home value, the replacement cost of structures, land value, and the home price index"
                                
                                
                                
                                
                        )
                )
        ))